### ISSUE TITLE
Race Condition: table "ACF" does not exist

### ISSUE THREAD

**Issue by MagnumMacKivler** [looterz/ACF-Sounds#1]
```
[ACF Sound Extension Project] lua/acf-sounds/shared.lua:33: attempt to index global 'ACF' (a nil value)
  1. ACF_ADD_SOUND - lua/acf-sounds/shared.lua:33
   2. ACF_SOUND_BUILD - lua/acf-sounds/shared.lua:142
    3. v - lua/acf-sounds/shared.lua:168
     4. unknown - lua/includes/modules/hook.lua:84
```

Your hook on InitPostEntity assumes the ACF table exists but if this is loaded before ACF itself, the table doesn't exist at runtime. This is especially fun because it prevents other addons that use InitPostEntity from running if their hooks get run after this one.

This should be easily fixed by wrapping everything within that hook in a timer.Simple for a couple seconds.

**Comment by looterz** [comment]
That should do the trick, thanks for the report.
